version: "3.9"
services:
  proxy:
    image: docker.int.justinmccormick.com/docker-nginx-ssl-proxy
    build: ./
    ports:
      - 0.0.0.0:443:443
    environment:
     - HOSTNAMES=server1.local,server1.local
     - TARGETS=http://192.168.1.43:5000,http://192.168.1.43:8080

# networks:
#   default:
#     external: true
#     name: host