version: "3.9"
services:
  proxy:
    build: ./
    ports:
      - 0.0.0.0:443:443
    environment:
     - HOSTNAME=energysmartwaterheater.com
    #  - HOSTNAME=devices.irissmarthome.com
     - TARGET_PORT=80

# networks:
#   default:
#     external: true
#     name: host