version: "3.9"
services:
  proxy:
    build: ./
    ports:
      - 0.0.0.0:443:443
    environment:
     - HOSTNAMES=server1.local,server2.local
     - TARGETS=http://192.168.1.2:5000,http://192.168.1.3:8080

# networks:
#   default:
#     external: true
#     name: host